name: mlops-aishield
on: [push]
    
jobs:
  run:
    runs-on: [ubuntu-latest]
    #container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r ./requirement.txt
          python ./extraction_reference_implementation_mnist.py
          
          echo "## extraction implementationModel Metrics" > report.md
          #cat /home/runner/work/ml-ops-ci/ml-ops-ci/reports/Attack_samples.zip >> Attack_samples.zip
          #cat /home/runner/work/ml-ops-ci/ml-ops-ci/reports/Defense_artifact.zip >> Defense_artifact.zip
          
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          #cml-publish model_results.png --md >> report.md
          
          #cml-send-comment report.md
